---
language: python
python: "2.7"
sudo: required
dist: trusty

# environment variables
env:
  - ANSIBLE_INVENTORY=hosts

# update apt indices, install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev python-pip gcc git

# install ansible from pip
install:
  - pip install --upgrade pip
  - pip install --upgrade ansible

# run tests
script:
  # run syntax checks
  - "ansible-playbook tests/test.yml -i tests/hosts --connection=local --syntax-check"

  # run score tasks
  - "travis_wait 20 ansible-playbook tests/test.yml -i tests/hosts --connection=local --tags=scored"

# vim: set sw=2 ts=2:
