---
#file: tasks/section-08-level-2.yml

# NOTE: It makes logical sense to install auditd first, then configuring it!
# And not vice-versa as is implied in the section ordering
- name: 8.1.2 Install and Enable auditd Service (Scored)
  apt: name=auditd update_cache=yes state=installed
  tags:
    - scored
    - section8.1.2

- name: 8.1.2 Install and Enable auditd Service (Scored)
  service: name=auditd state=started enabled=yes
  tags:
    - scored
    - section8.1.2

- name: 8.1.1 Configure Data Retention
  debug: msg="*** When auditing, it is important to carefully configure the storage requirements for audit logs"
  tags:
    - section8.1.1

- name: 8.1.1.1 Configure Audit Log Storage Size (Not Scored)
  lineinfile: dest=/etc/audit/auditd.conf regexp="^max_log_file" line="max_log_file = 10" state=present
  notify: restart auditd
  tags:
    - notscored
    - section8.1.1
    - section8.1.1.1

- name: 8.1.1.2 Disable System on Audit Log Full (Not Scored)
  lineinfile: dest="/etc/audit/auditd.conf" regexp="{{item.regex}}" line="{{item.line}}"
  with_items:
    - { regex: "^space_left_action", line: "space_left_action = email" }
    - { regex: "^action_mail_acct", line: "action_mail_acct = root" }
    - { regex: "^admin_space_left_action", line: "admin_space_left_action = halt" }
  notify: restart auditd
  tags:
    - notscored
    - section8.1.1
    - section8.1.1.2

- name: 8.1.1.3 Keep All Auditing Information (Scored)
  lineinfile: dest="/etc/audit/auditd.conf" regexp="^max_log_file_action" line="max_log_file_action = keep_logs" state=present
  notify: restart auditd
  tags:
    - scored
    - section8.1.1
    - section8.1.1.3

#TODO: find a way to append at the end of a line
- name: 8.1.3 Enable Auditing for Processes That Start Prior to auditd (Scored)
  debug: msg="***  Adjusting bootloader configurations on production machines can be destructive."
    - section8.1.3

- name: 8.1.4 Record Events That Modify Date and Time Information (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change"
    - "-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change"
    - "-a always,exit -F arch=b64 -S clock_settime -k time-change"
    - "-a always,exit -F arch=b32 -S clock_settime -k time-change"
    - "-w /etc/localtime -p wa -k time-change"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.4

- name: 8.1.4 Record Events That Modify Date and Time Information (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change"
    - "-a always,exit -F arch=b32 -S clock_settime -k time-change"
    - "-w /etc/localtime -p wa -k time-change"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.4

- name: 8.1.5 Record Events That Modify User/Group Information (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /etc/group -p wa -k identity"
    - "w /etc/passwd -p wa -k identity"
    - "-w /etc/gshadow -p wa -k identity"
    - "-w /etc/shadow -p wa -k identity"
    - "-w /etc/security/opasswd -p wa -k identity"
  notify: restart auditd
  tags:
    - scored
    - section8.1.5

- name: 8.1.6 Record Events That Modify the System's Network Environment(Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a exit,always -F arch=b64 -S sethostname -S setdomainname -k system-locale"
    - "-a exit,always -F arch=b32 -S sethostname -S setdomainname -k system-locale"
    - "-w /etc/issue -p wa -k system-locale"
    - "-w /etc/issue.net -p wa -k system-locale"
    - "-w /etc/hosts -p wa -k system-locale"
    - "-w /etc/network -p wa -k system-locale"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.6

- name: 8.1.6 Record Events That Modify the System's Network Environment(Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a exit,always -F arch=b32 -S sethostname -S setdomainname -k system-locale"
    - "-w /etc/issue -p wa -k system-locale"
    - "-w /etc/issue.net -p wa -k system-locale"
    - "-w /etc/hosts -p wa -k system-locale"
    - "-w /etc/network -p wa -k system-locale"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.6

- name: 8.1.7 Record Events That Modify the System's Mandatory Access Controls (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="-w /etc/selinux/ -p wa -k MAC-policy" insertafter=EOF state=present
  notify: restart auditd
  tags:
    - scored
    - section8.1.7

- name: 8.1.8 Collect Login and Logout Events (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /var/log/faillog -p wa -k logins"
    - "-w /var/log/lastlog -p wa -k logins"
    - "-w /var/log/tallylog -p wa -k logins"
  notify: restart auditd
  tags:
    - scored
    - section8.1.8

- name: 8.1.9 Collect Session Initiation Information (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /var/run/utmp -p wa -k session"
    - "-w /var/log/wtmp -p wa -k session"
    - "-w /var/log/btmp -p wa -k session"
  notify: restart auditd
  tags:
    - scored
    - section8.1.9

- name: 8.1.10 Collect Discretionary Access Control Permission Modification Events (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=500 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=500 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.10

- name: 8.1.10 Collect Discretionary Access Control Permission Modification Events (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=500 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=500 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.10

- name: 8.1.11 Collect Unsuccessful Unauthorized Access Attempts to Files (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate"
    - "-F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate"
    - "-F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate"
    - "-F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate"
    - "-F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.11

- name: 8.1.11 Collect Unsuccessful Unauthorized Access Attempts to Files (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.11

- name: 8.1.12 Collect Use of Privileged Commands (Scored)
  shell: /bin/find {/usr/local/sbin,/usr/local/bin,/sbin,/bin,/usr/sbin,/usr/bin} -xdev \( -perm -4000 -o -perm -2000 \) -type f | awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=500 -F auid!=4294967295 -k privileged" }'
  register: privileged_programs
  tags:
    - scored
    - section8.1.12

- name: 8.1.12 Collect Use of Privileged Commands (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items: privileged_programs.stdout_lines
  when: privileged_programs is defined and privileged_programs.stdout_lines|length > 0
  notify: restart auditd
  tags:
    - scored
    - section8.1.12

- name: 8.1.13 Collect Successful File System Mounts (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S mount -F auid>=500 -F auid!=4294967295 -k mounts"
    - "-a always,exit -F arch=b32 -S mount -F auid>=500 -F auid!=4294967295 -k mounts"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.13

- name: 8.1.13 Collect Successful File System Mounts (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S mount -F auid>=500 -F auid!=4294967295 -k mounts"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.13

- name: 8.1.14 Collect File Deletion Events by User (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete"
    - "-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.14

- name: 8.1.14 Collect File Deletion Events by User (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.14

- name: 8.1.15 Collect Changes to System Administration Scope (sudoers) (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /etc/sudoers -p wa -k scope"
  notify: restart auditd
  tags:
    - scored
    - section8.1.15

- name: 8.1.16 Collect System Administrator Actions (sudolog) (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /var/log/sudo.log -p wa -k actions"
  notify: restart auditd
  tags:
    - scored
    - section8.1.16

- name: 8.1.17 Collect Kernel Module Loading and Unloading (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /sbin/insmod -p x -k modules"
    - "-w /sbin/rmmod -p x -k modules"
    - "-w /sbin/modprobe -p x -k modules"
    - "-a always,exit -F arch=b64 -S init_module -S delete_module -k modules"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.17

- name: 8.1.17 Collect Kernel Module Loading and Unloading (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="{{item}}" insertafter=EOF state=present
  with_items:
    - "-w /sbin/insmod -p x -k modules"
    - "-w /sbin/rmmod -p x -k modules"
    - "-w /sbin/modprobe -p x -k modules"
    - "-a always,exit -F arch=b32 -S init_module -S delete_module -k modules"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.17

- name: 8.1.18 Make the Audit Configuration Immutable (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="-e 2" insertafter=EOF state=present
  notify: restart auditd
  tags:
    - scored
    - section8.1.18

- name: 8.2 Configure rsyslog
  debug: msg="*** rsyslog provides improvements over syslogd, such as connection-oriented (i.e. TCP) transmission of logs logging to database formats and encryption of log data during transmission."
  tags:
    - section8.2

- name: 8.2.1 Install the rsyslog package (Scored)
  apt: name=rsyslog update_cache=yes state=installed
  tags:
    - scored
    - section8.2
    - section8.2.1

- name: 8.2.2 Ensure the rsyslog Service is activated (Scored)
  service: name=rsyslog state=started enabled=yes
  tags:
    - scored
    - section8.2
    - section8.2.2

- name: 8.2.3 Configure /etc/rsyslog.conf (Not Scored)
  copy: src=rsyslog.d/CIS.conf dest=/etc/rsyslog.d/CIS.conf owner=root group=root mode=0644
  notify: restart rsyslog
  tags:
    - notscored
    - section8.2
    - section8.2.3

- name: 8.2.4 Create and Set Permissions on rsyslog Log Files (Scored)
  lineinfile: dest=/etc/rsyslog.conf regexp='^\$FileCreateMode' line="$FileCreateMode 0640" insertafter=EOF state=present
  notify: restart rsyslog
  tags:
    - scored
    - section8.2
    - section8.2.4

- name: 8.2.5 Configure rsyslog to Send Logs to a Remote Log Host (Scored)
  debug: msg="*** Evaluate your infrastructure first, before sending logs to remote host"
  tags:
    - scored
    - section8.2
    - section8.2.5

- name: 8.2.6 Accept Remote rsyslog Messages Only on Designated Log Hosts (Not Scored)
  debug: msg="*** Evaluate your infrastructure first, before receiving logs from remote host(s)"
  tags:
    - scored
    - section8.2
    - section8.2.6

- name: 8.3 Advanced Intrusion Detection Environment (AIDE)
  debug: msg="*** AIDE detects unauthorized changes to configuration files by alerting when the files are changed"
  tags:
    - section8.3

- name: 8.3.1 Install AIDE (Scored)
  apt: name=aide update_cache=yes state=present
  notify: initialize aide
  tags:
    - scored
    - section8.3
    - section8.3.1

- name: 8.3.2 Implement Periodic Execution of File Integrity (Scored)
  copy: src=aide/aide.cron dest=/etc/cron.daily/aide.cron owner=root group=root mode=0755
  tags:
    - scored
    - section8.3
    - section8.3.2

- name: 8.4 Configure logrotate (Not Scored)
  debug: msg="*** Review /etc/logrotate.d/rsyslog to determine if the appropriate system logs are rotated according to your site policy"
  tags:
    - notscored
    - section8.4

# vim: set sw=2 ts=2:
